WeatherApp/Models/ErrorViewModel.cs
namespace WeatherApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WeatherApp/Models/Weather.cs
using System.Text.Json.Serialization;

namespace WeatherApp.Models;

[Serializable]
public class Weather
{
    [JsonPropertyName("date")]
    public DateOnly Date { get; set; }

    [JsonPropertyName("temperatureC")]
    public int TemperatureC { get; set; }

    [JsonPropertyName("summary")]
    public string? Summary { get; set; }
}

WeatherApp/Models/WeatherDto.cs
using System.Text.Json.Serialization;

namespace WeatherApp.Models;

[Serializable]
public class WeatherDto
{
    [JsonPropertyName("date")]
    public DateOnly Date { get; set; }

    [JsonPropertyName("temperatureC")]
    public int TemperatureC { get; set; }

    [JsonPropertyName("summary")]
    public string? Summary { get; set; }
}

WeatherApp/ViewModels/WeatherModel.cs
using WeatherApp.Models;

namespace WeatherApp.ViewModels;

public class WeatherViewModel
{
    public string City { get; set; }
    
    public List<WeatherDto> Weather { get; set; }
}

WeatherApp/Controllers/AuthenticationController.cs
using IdentityModel.Client;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using WeatherApp.Exceptions;

namespace WeatherApp.Controllers;

public class AuthenticationController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public AuthenticationController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    [Authorize]
    public async Task Logout()
    {
        var idpClient = _httpClientFactory.CreateClient("IDPClient");

        var discoveryDocument = await idpClient.GetDiscoveryDocumentAsync();

        if (discoveryDocument == null) throw new ObjectIsNullException("Discovery document is null!");

        /*var accessTokenOperationResponse = await idpClient.RevokeTokenAsync(new TokenRevocationRequest()
        {
            Address = discoveryDocument.RevocationEndpoint,
            ClientId = "weatherclient",
            ClientSecret = "secret",
            Token = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.AccessToken)
        });

        if (accessTokenOperationResponse.IsError)
        {
            
        }*/
        
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
        
    }

    public IActionResult ActionDenied()
    {
        return View();
    }
}

WeatherApp/Controllers/HomeController.cs
using System.Diagnostics;
using System.Text;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Protocols.OpenIdConnect;
using WeatherApp.Models;

namespace WeatherApp.Controllers;

[Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public async Task<IActionResult> Index()
    {
        await LogTokenAsync();
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public async Task LogTokenAsync()
    {
        var identityToken = await HttpContext.GetTokenAsync(OpenIdConnectParameterNames.IdToken);


        var userClaimsBuilder = new StringBuilder();
        foreach (var claim in User.Claims)
        {
            userClaimsBuilder.AppendLine($"Claim type: {claim.Type} - Claim value: {claim.Value}");
        }

        _logger.LogInformation($"IdentityToken is {identityToken} and \n claims {userClaimsBuilder}");
    }
}

WeatherApp/Controllers/WeatherController.cs
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WeatherApp.Models;
using WeatherApp.ViewModels;

namespace WeatherApp.Controllers;

[Authorize(Policy = "CanGetWeather")]
public class WeatherController : Controller
{
    private readonly IHttpClientFactory _httpClientFactory;

    public WeatherController(IHttpClientFactory httpClientFactory)
    {
        _httpClientFactory = httpClientFactory;
    }

    public IActionResult Index()
    {
        var vm = new WeatherViewModel();
        return View(vm);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(string city, CancellationToken cancellationToken)
    {
        var client = _httpClientFactory.CreateClient("WeatherApiClient");
        
        var request = new HttpRequestMessage(HttpMethod.Get, "/WeatherForecast");

        var response = await client.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken);

        response.EnsureSuccessStatusCode();
        
        using (var stream = await response.Content.ReadAsStreamAsync(cancellationToken))
        {
            var forecasts =
                await JsonSerializer.DeserializeAsync<List<WeatherDto>>(stream, cancellationToken: cancellationToken);
            return View(new WeatherViewModel
            {
                City = city,
                Weather = forecasts
            });
        }
    }
}

WeatherApp/Views/Authentication/ActionDenied.cshtml
<h1>Action Denied</h1>

<p>You do not have permission to access this page.</p>

WeatherApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WeatherApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WeatherApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WheatherApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeatherApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication" asp-action="Logout">Logout</a>
                        </li>
                        if ((await AuthorizationService.AuthorizeAsync(User, "CanGetWeather")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Weather" asp-action="Index">Weather</a>
                            </li>
                        }
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WeatherApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WeatherApp/Views/Weather/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model WeatherApp.ViewModels.WeatherViewModel

<h3>Weather Report</h3>

<form method="post">
    <div class="form-group">
        <label for="city">City:</label>
        <input type="text" class="form-control" id="city" name="city">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

@if (Model?.Weather != null)
{
    foreach (var w in Model.Weather)
    {
        <div>
            <h4>Current weather in @Model.City:</h4>
            <p>Temperature: @w.TemperatureC &#8451;</p>
            <p>Humidity: @w.Date %</p>
            <p>Description: @w.Summary</p>
        </div>
    }

}